### ISSUE TITLE
Flycheck error: Symbol’s value as variable is void: filename

### ISSUE THREAD

**Issue by cobac** [dmalyuta/julia-staticlint#1]
Hey.

I was trying to use your package but I cannot manage to get it working. Flycheck returns the following error:

```
Error from syntax checker julia-staticlint: Symbol’s value as variable is void: filename
```

I'm running

- Emacs 27
- lsp disabled
- flycheck selecting staticlint
- julia-staticlint installed from source
- StaticLint, SymbolServer, Printf, and Sockets installed

I can replicate the error with the following init:

```elisp

;; Straight.el things to pull from source
(setq straight-recipes-gnu-elpa-use-mirror t)

(defvar bootstrap-version)
(let ((bootstrap-file
			 (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
			(bootstrap-version 5))
	(unless (file-exists-p bootstrap-file)
		(with-current-buffer
				(url-retrieve-synchronously
				 "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
				 'silent 'ihibit-cookies)
			(goto-char (point-max))
			(eval-print-last-sexp)))
	(load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)

(use-package flycheck
	:straight t
	:config
  (global-flycheck-mode)
	)

(use-package julia-mode
  :straight t
  )

(use-package julia-staticlint
  :straight (:type git :host github :repo "dmalyuta/julia-staticlint")
  :hook ((julia-mode . julia-staticlint-activate))
  :config
  (julia-staticlint-init))

```

I get the same error with individual .jl files and inside packages. I am not really sure how to trace what's going on. Thank you for your work!

**Comment by dmalyuta** [comment]
Thank you for your comment and interest! I think I narrowed down your issue to the `.jl` files of this repo being ignored by `straight` (by default, `straight` only uses the `julia-staticlint.el` file, but remember that there is also a client and a server Julia file in this repo that are needed to communicate with StaticLint). There is some [documentation](https://github.com/raxod502/straight.el#the-recipe-format) on how to do this in `straight`. In your init, changing the `julia-staticlint` part to the following seems to work for me:

```
(use-package julia-staticlint
  :straight (:type git :host github :repo "dmalyuta/julia-staticlint"
		   :files ("julia-staticlint.el"
			   "julia_staticlint_server.jl"
			   "julia_staticlint_client.jl"))
  :hook ((julia-mode . julia-staticlint-activate))
  :config
  (julia-staticlint-init))
```

The error that you were seeing is due to the Elisp code in `julia-staticlint.el` trying to call `julia_staticlint_client.jl`, but not finding it because it is not installed properly. I identified this error by doing `M-x toggle-debug-on-error` after startup and then opening a Julia file. The error that you observe then shows a backtrace, where it was visible that the `julia_staticlint_client.jl` was not being found.

**Comment by cobac** [comment]
Hey, thanks so much for your answer and for educating me about Emacs debugging :smile: 

So now the package is loaded and flychek does not spill any loading errors, but it doesn't display any linting either. I can reproduce this with the init.el I provided above with your use-package julia-staticlint macro.
 
However, I've managed to get linting from lsp-julia using the LanguageServer image they ship. I will happily help to test why staticlint is not working in my environment if you are interested though.

**Comment by dmalyuta** [comment]
Interesting. What is the output that you see in the buffer `*julia-staticlint-server*`?

In general, here is how we could start to diagnose the issue. First, create the following file with the path `/tmp/foobar.jl` (or any other folder, I'll just use that as an example):
```
using LinearAlgebras

struct Buz
    x::Integers
    α::Array{Float65,1}
end

function bar(x::Integer, y::Float64)::Integer
    return x
end
```

Now open up one terminal, navigate to the folder where you cloned this repository, and in it run:
```
$ julia julia_staticlint_server.jl
```

For me, this outputs (after 10-30 seconds, when StaticLint has configured itself):
```
$ julia julia_staticlint_server.jl
Initializing server
Started server
```

Now open another terminal, again navigate to the folder where you cloned this repository, and in it run:
```
$ julia julia_staticlint_client.jl /tmp/foobar.jl
```

This command asks the server to check errors in the `foobar.jl` file. For me, this outputs (the previous terminal with the server stays silent):
```
$ julia julia_staticlint_client.jl /tmp/foobar.jl
/tmp/foobar.jl:7:21: error: Missing reference for LinearAlgebras
/tmp/foobar.jl:41:49: error: Missing reference for Integers
/tmp/foobar.jl:63:70: error: Missing reference for Float65
/tmp/foobar.jl:104:114: error: An argument is included in a function signature but not used within its body.
```

Could you tell me if all of the above works for you? If not, what errors do you see?

**Comment by cobac** [comment]
Looking at `*julia-staticlint-server*`  I saw that CSTParser was not installed, although StaticLint.jl should depend on it (?). After installing it I get `ERROR: LoadError: UndefVarError: headof not defined` from the call at `julia_staticlint_server.jl:6`. I obviously get the same error after trying to start the server manually.

I've tried rebuilding the dependencies with `Pkg.build(["SymbolServer","StaticLint","Printf","Sockets"])`.

I've tried editing `julia_staticlint_server.jl:6` to import `headof`in the last place and then it fails to import `isnonstdid`. Repeating this process I've narrowed that:

- Fails to import `headof`, `isnonstdid` and `iscal`.
- `EXPR`, `isidentifier` and  `valof` are imported correctly.

Unfortunately I am not familiar with Julia yet so I can only do this hack-y debugging :sweat:.

Thanks again.

**Comment by dmalyuta** [comment]
Hmm interesting. What is the output of (in the Julia command line): `using Pkg; Pkg.status("CSTParser")`? Also, perhaps the reason the import fails is due to an old version of CSTParser installed, in which case try running in the Julia command line:
```
using Pkg
Pkg.add(PackageSpec(url="https://github.com/julia-vscode/StaticLint.jl"))
Pkg.add(PackageSpec(url="https://github.com/julia-vscode/SymbolServer.jl"))
Pkg.add(PackageSpec(url="https://github.com/julia-vscode/CSTParser.jl"))
```
Does this fix the import issue? To be clear, since these are Julia issues, we are debugging the Julia installation here and not the Emacs package.

**Comment by cobac** [comment]
At this point I feel bad about using your issues tracker for this. My local copy of the General registry is up to date, but my packages were not upgrading to the latest versions. I've reinstalled my whole Julia environment and now everything works and all packages are updated correctly. I am not sure what could have caused my packages not to upgrade. Thanks anyway for your time :smile: .
