### ISSUE TITLE
Publish on MELPA?

### ISSUE THREAD

**Issue by kir0ul** [dmalyuta/julia-staticlint#2]
Hi there,

Thanks for this very useful package!

I was wondering if you would consider publishing it to [MELPA](https://melpa.org/) so that it's easier to find, install and update?

**Comment by dmalyuta** [comment]
Thanks! I don't plan to put it on MELPA due to a lack of time on my part to do so. I would recommend using [Quelpa](https://github.com/quelpa/quelpa) to load the package automatically, as the README suggests:

```
(use-package julia-staticlint
  ;; https://github.com/dmalyuta/julia-staticlint
  ;; Emacs Flycheck support for StaticLint.jl
  :ensure nil
  :quelpa ((julia-staticlint :fetcher github
			       :repo "dmalyuta/julia-staticlint"
			       :files (:defaults "julia_staticlint_server.jl"
						 "julia_staticlint_client.jl")))
  :hook ((julia-mode . julia-staticlint-activate))
  :config
  (julia-staticlint-init))
```
